export const Questions = [
    {
      prompt: "Identify the option that is NOT a type of operating system.",
      optionA: "Real-time OS",
      optionB: "Multi-user OS",
      optionC: "Single-tasking OS",
      optionD: "Batch processing OS",
      answer: "C",
    },
    {
      prompt: "What operating system is developed by Microsoft?",
      optionA: "Linux",
      optionB: "macOS",
      optionC: "Windows",
      optionD: "Android",
      answer: "C",
    },
    {
      prompt: "Name the OS commonly used for mobile devices.",
      optionA: "Windows",
      optionB: "macOS",
      optionC: "Android",
      optionD: "Linux",
      answer: "C",
    },
    {
      prompt: "Identify the open-source operating system.",
      optionA: "Windows",
      optionB: "Linux",
      optionC: "iOS",
      optionD: "macOS",
      answer: "B",
    },
    {
      prompt: "What component of the OS manages files?",
      optionA: "File System",
      optionB: "Kernel",
      optionC: "Shell",
      optionD: "Memory Manager",
      answer: "A",
    },
    {
      prompt: "In UNIX, what command lists files in a directory?",
      optionA: "ls",
      optionB: "dir",
      optionC: "list",
      optionD: "show",
      answer: "A",
    },
    {
      prompt: "What is the core of an operating system called?",
      optionA: "Kernel",
      optionB: "Shell",
      optionC: "Command Line Interface",
      optionD: "Device Manager",
      answer: "A",
    },
    {
      prompt: "Which OS is popular for servers and mainframes?",
      optionA: "macOS",
      optionB: "Linux",
      optionC: "Android",
      optionD: "Windows",
      answer: "B",
    },
    {
      prompt: "What scheduling algorithm do most operating systems use for multitasking?",
      optionA: "Round Robin",
      optionB: "FIFO",
      optionC: "Shortest Job First",
      optionD: "Priority Scheduling",
      answer: "A",
    },
    {
      prompt: "What command is used to shut down a Windows computer?",
      optionA: "exit",
      optionB: "shutdown",
      optionC: "stop",
      optionD: "close",
      answer: "B",
    },
  ];
  