export const Questions = [
    {
      prompt: "Which of the following is NOT a type of operating system?",
      optionA: "Real-time OS",
      optionB: "Multi-user OS",
      optionC: "Single-tasking OS",
      optionD: "Batch processing OS",
      answer: "C",
    },
    {
      prompt: "Which operating system is developed by Microsoft?",
      optionA: "Linux",
      optionB: "macOS",
      optionC: "Windows",
      optionD: "Android",
      answer: "C",
    },
    {
      prompt: "What is the main purpose of an operating system?",
      optionA: "To manage resources and provide services for software",
      optionB: "To increase the speed of the CPU",
      optionC: "To serve as the hardware",
      optionD: "To provide network access",
      answer: "A",
    },
    {
      prompt: "Which of the following is an open-source operating system?",
      optionA: "Windows",
      optionB: "Linux",
      optionC: "iOS",
      optionD: "macOS",
      answer: "B",
    },
    {
      prompt: "Which component of the OS is responsible for managing files?",
      optionA: "File System",
      optionB: "Kernel",
      optionC: "Shell",
      optionD: "Memory Manager",
      answer: "A",
    },
    {
      prompt: "In UNIX, what is the command to list files in a directory?",
      optionA: "ls",
      optionB: "dir",
      optionC: "list",
      optionD: "show",
      answer: "A",
    },
    {
      prompt: "What is the core of an operating system?",
      optionA: "Kernel",
      optionB: "Shell",
      optionC: "Command Line Interface",
      optionD: "Device Manager",
      answer: "A",
    },
    {
      prompt: "Which OS is known for its use in servers and mainframes?",
      optionA: "macOS",
      optionB: "Linux",
      optionC: "Android",
      optionD: "Windows",
      answer: "B",
    },
    {
      prompt: "Which scheduling algorithm is used by most operating systems for multitasking?",
      optionA: "Round Robin",
      optionB: "FIFO",
      optionC: "Shortest Job First",
      optionD: "Priority Scheduling",
      answer: "A",
    },
    {
      prompt: "What does the acronym GUI stand for?",
      optionA: "Graphical User Interface",
      optionB: "General User Interface",
      optionC: "Guided User Input",
      optionD: "Global User Interface",
      answer: "A",
    },
  ];
  